// <auto-generated />
using System;
using Dental_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dental_App.Migrations
{
    [DbContext(typeof(Dental_App.Models.AppContext))]
    [Migration("20260212191400_InitialSQLiteCreate")]
    partial class InitialSQLiteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("ActeConsultation", b =>
                {
                    b.Property<int>("IdConsul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdActe")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdConsul", "IdActe")
                        .HasName("PK__ActeCons__205BE8A7DAD9A0EC");

                    b.HasIndex("IdActe");

                    b.ToTable("ActeConsultation", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.ActeMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__ActeMedi__3214EC075F8B031D");

                    b.ToTable("ActeMedical", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Antecedant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Anteceda__3214EC07B461AA38");

                    b.ToTable("Antecedant", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Caisse", b =>
                {
                    b.Property<DateOnly>("DateDuJour")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Montant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("DateDuJour")
                        .HasName("PK__Caisse__60CDBF3EC933E1D1");

                    b.ToTable("Caisse", null, t =>
                        {
                            t.HasTrigger("tr_Caisse_Upsert");
                        });
                });

            modelBuilder.Entity("Dental_App.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdDent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC070B62EC18");

                    b.HasIndex("IdDent");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultation", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Dent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeFdi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CodeFDI");

                    b.HasKey("Id")
                        .HasName("PK__Dent__3214EC07A95B2285");

                    b.ToTable("Dent", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Medicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdonnanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posologie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Medicame__3214EC0705259ACA");

                    b.HasIndex("OrdonnanceId");

                    b.ToTable("Medicament", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.OdontogrammeLibre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InkFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Odontogr__3214EC078C2999DB");

                    b.HasIndex("PatientId");

                    b.ToTable("OdontogrammeLibre", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Ordonnan__3214EC0769A52545");

                    b.HasIndex("PatientId");

                    b.ToTable("Ordonnance", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CIN");

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SommePaye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Patient__3214EC078A5281F7");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.RadioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatePrise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__RadioIma__3214EC07261052E2");

                    b.HasIndex("PatientId");

                    b.ToTable("RadioImage", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.RendezVou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__RendezVo__3214EC07CC1B80E1");

                    b.HasIndex("PatientId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("Dental_App.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Utilisat__3214EC0709A8F6B9");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("PatientAntecedant", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAntecedant")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPatient", "IdAntecedant")
                        .HasName("PK__PatientA__798C43F908F64248");

                    b.HasIndex("IdAntecedant");

                    b.ToTable("PatientAntecedant", (string)null);
                });

            modelBuilder.Entity("ActeConsultation", b =>
                {
                    b.HasOne("Dental_App.Models.ActeMedical", null)
                        .WithMany()
                        .HasForeignKey("IdActe")
                        .IsRequired()
                        .HasConstraintName("FK_ActeConsul_Acte");

                    b.HasOne("Dental_App.Models.Consultation", null)
                        .WithMany()
                        .HasForeignKey("IdConsul")
                        .IsRequired()
                        .HasConstraintName("FK_ActeConsul_Consul");
                });

            modelBuilder.Entity("Dental_App.Models.Consultation", b =>
                {
                    b.HasOne("Dental_App.Models.Dent", "IdDentNavigation")
                        .WithMany("Consultations")
                        .HasForeignKey("IdDent")
                        .HasConstraintName("FK_Consultation_Dent");

                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Consultation_Patient");

                    b.Navigation("IdDentNavigation");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.Medicament", b =>
                {
                    b.HasOne("Dental_App.Models.Ordonnance", "Ordonnance")
                        .WithMany("Medicaments")
                        .HasForeignKey("OrdonnanceId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicament_Ordonnance");

                    b.Navigation("Ordonnance");
                });

            modelBuilder.Entity("Dental_App.Models.OdontogrammeLibre", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("OdontogrammeLibres")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Odontogramme_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("Ordonnances")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Ordonnance_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.RadioImage", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("RadioImages")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_RadioImage_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.RendezVou", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_RendezVous_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientAntecedant", b =>
                {
                    b.HasOne("Dental_App.Models.Antecedant", null)
                        .WithMany()
                        .HasForeignKey("IdAntecedant")
                        .IsRequired()
                        .HasConstraintName("FK_PatAnt_Ant");

                    b.HasOne("Dental_App.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("IdPatient")
                        .IsRequired()
                        .HasConstraintName("FK_PatAnt_Patient");
                });

            modelBuilder.Entity("Dental_App.Models.Dent", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.Navigation("Medicaments");
                });

            modelBuilder.Entity("Dental_App.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("OdontogrammeLibres");

                    b.Navigation("Ordonnances");

                    b.Navigation("RadioImages");

                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
