// <auto-generated />
using System;
using Dental_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dental_App.Migrations
{
    [DbContext(typeof(DentalContext))]
    partial class DentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("ActeConsultation", b =>
                {
                    b.Property<int>("IdConsul")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdActe")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdConsul", "IdActe");

                    b.HasIndex(new[] { "IdActe" }, "IX_ActeConsultation_IdActe");

                    b.ToTable("ActeConsultation", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.ActeMedical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("ActeMedical", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Antecedant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Antecedant", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Caisse", b =>
                {
                    b.Property<string>("DateDuJour")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Montant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0.0m);

                    b.HasKey("DateDuJour");

                    b.ToTable("Caisse", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.CommandeProthesiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achats")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdProthesiste")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id_Prothesiste");

                    b.Property<double?>("SommePayees")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0)
                        .HasColumnName("Somme_Payees");

                    b.HasKey("Id");

                    b.HasIndex("IdProthesiste");

                    b.ToTable("Commande_Prothesiste", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdDent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdDent" }, "IX_Consultation_IdDent");

                    b.HasIndex(new[] { "PatientId" }, "IX_Consultation_PatientId");

                    b.ToTable("Consultation", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Dent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeFdi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CodeFDI");

                    b.HasKey("Id");

                    b.ToTable("Dent", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Medicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdonnanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Posologie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrdonnanceId" }, "IX_Medicament_OrdonnanceId");

                    b.ToTable("Medicament", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.OdontogrammeLibre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InkFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "IX_OdontogrammeLibre_PatientId");

                    b.ToTable("OdontogrammeLibre", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "IX_Ordonnance_PatientId");

                    b.ToTable("Ordonnance", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cin")
                        .HasColumnType("TEXT")
                        .HasColumnName("CIN");

                    b.Property<string>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SommePaye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.Prothesiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prothesiste", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.RadioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatePrise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "IX_RadioImage_PatientId");

                    b.ToTable("RadioImage", (string)null);
                });

            modelBuilder.Entity("Dental_App.Models.RendezVou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "IX_RendezVous_PatientId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("Dental_App.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("PatientAntecedant", b =>
                {
                    b.Property<int>("IdPatient")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAntecedant")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPatient", "IdAntecedant");

                    b.HasIndex(new[] { "IdAntecedant" }, "IX_PatientAntecedant_IdAntecedant");

                    b.ToTable("PatientAntecedant", (string)null);
                });

            modelBuilder.Entity("ActeConsultation", b =>
                {
                    b.HasOne("Dental_App.Models.ActeMedical", null)
                        .WithMany()
                        .HasForeignKey("IdActe")
                        .IsRequired();

                    b.HasOne("Dental_App.Models.Consultation", null)
                        .WithMany()
                        .HasForeignKey("IdConsul")
                        .IsRequired();
                });

            modelBuilder.Entity("Dental_App.Models.CommandeProthesiste", b =>
                {
                    b.HasOne("Dental_App.Models.Prothesiste", "IdProthesisteNavigation")
                        .WithMany("CommandeProthesistes")
                        .HasForeignKey("IdProthesiste")
                        .IsRequired();

                    b.Navigation("IdProthesisteNavigation");
                });

            modelBuilder.Entity("Dental_App.Models.Consultation", b =>
                {
                    b.HasOne("Dental_App.Models.Dent", "IdDentNavigation")
                        .WithMany("Consultations")
                        .HasForeignKey("IdDent");

                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("IdDentNavigation");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.Medicament", b =>
                {
                    b.HasOne("Dental_App.Models.Ordonnance", "Ordonnance")
                        .WithMany("Medicaments")
                        .HasForeignKey("OrdonnanceId")
                        .IsRequired();

                    b.Navigation("Ordonnance");
                });

            modelBuilder.Entity("Dental_App.Models.OdontogrammeLibre", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("OdontogrammeLibres")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("Ordonnances")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.RadioImage", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("RadioImages")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental_App.Models.RendezVou", b =>
                {
                    b.HasOne("Dental_App.Models.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientAntecedant", b =>
                {
                    b.HasOne("Dental_App.Models.Antecedant", null)
                        .WithMany()
                        .HasForeignKey("IdAntecedant")
                        .IsRequired();

                    b.HasOne("Dental_App.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("IdPatient")
                        .IsRequired();
                });

            modelBuilder.Entity("Dental_App.Models.Dent", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Dental_App.Models.Ordonnance", b =>
                {
                    b.Navigation("Medicaments");
                });

            modelBuilder.Entity("Dental_App.Models.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("OdontogrammeLibres");

                    b.Navigation("Ordonnances");

                    b.Navigation("RadioImages");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Dental_App.Models.Prothesiste", b =>
                {
                    b.Navigation("CommandeProthesistes");
                });
#pragma warning restore 612, 618
        }
    }
}
